name: Build MobArena

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    branches: [ "main" ]

permissions:
  contents: write

jobs:

  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'microsoft'

    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build

    - name: Get Version
      run: |
        echo "Multi-Step Execution Test
        echo "::set-output name=version::$(git rev-parse --short "$GITHUB_SHA")"
        echo "End"
      id: version

    - name: Create Release
      uses: ncipollo/release-action@v1
      id: create_release
      with:
        latest: true
        draft: false
        prerelease: true
        artifacts: "build/libs/MobArena-1.0-SNAPSHOT.jar"
        name: ${{ steps.version.outputs.version }}
        tag: ${{ steps.version.outputs.version }}
        generateReleaseNotes: true
      env:
        GITHUB_TOKEN: ${{ github.token }}