name: Build MobArena

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'microsoft'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build

  publish:
    name: Publish

    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - name: Publish Release
        uses: Shopify/upload-to-release@v1
        with:
          name: MobArena.jar
          path: build/libs/MobArena-SNAPSHOT-1.0.0.jar
          repo-token: ${{ secrets.GITHUB_TOKEN }}